### PR TITLE
Sync User language from AAD.

### PR DESCRIPTION
**Pull request by schjan**
Gets Moodle's _lang_ property from Azure AD.

Altough the unittest is quite failing the code worked for me.
If anyone has an idea why the UnitTest isn't working I will fix it.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@schjan__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by msotclas** [comment]
__@schjan__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by jamesmcq** [comment]
Thanks schjan! I'll be reviewing this shortly.

**Comment by jamesmcq** [comment]
This has now been released, thanks again schjan!

**Pull request merged**
